function results = myimfcn(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------



% Replace the sample below with your code----------------------------------
im = imcrop(im,[12 427 1909 475]);
im = imrotate(im,-2);
indices = find(im>150);
im(indices) = 0;
if(size(im,3)==3)
    % Convert RGB to grayscale
    imgray = rgb2gray(im);
else
    imgray = im;
end


bw = imbinarize(imgray-30);

results.imgray = imgray;
results.bw     = bw;

%--------------------------------------------------------------------------
